// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7t5YxYV63R1BlRms3inU5yD-0FjxHPY',
    appId: '1:526077748693:web:b8033c11ed50245567095c',
    messagingSenderId: '526077748693',
    projectId: 'homeshine-31551',
    authDomain: 'homeshine-31551.firebaseapp.com',
    storageBucket: 'homeshine-31551.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-LKtiqPTD0i27DSS_Md8qiM2KoXH8WGY',
    appId: '1:526077748693:android:d4b7964919f5645367095c',
    messagingSenderId: '526077748693',
    projectId: 'homeshine-31551',
    storageBucket: 'homeshine-31551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttjshfp4oyuzE1wcZoE8fYaXwC1q9NXs',
    appId: '1:526077748693:ios:121b9f8f88f3309967095c',
    messagingSenderId: '526077748693',
    projectId: 'homeshine-31551',
    storageBucket: 'homeshine-31551.appspot.com',
    iosBundleId: 'com.example.houseKeepingPro',
  );
}
